### ISSUE TITLE
settings error in intellij idea

### ISSUE THREAD

**Issue by chenshaogu** [investflow/mqlidea#10]
I've got an error when i open setting panel
![image](https://user-images.githubusercontent.com/81604729/115485668-bf60aa00-a287-11eb-852f-7ab050e782c4.png)

![image](https://user-images.githubusercontent.com/81604729/115485847-0b135380-a288-11eb-87b2-893644acdac2.png)

I guess the possible error is that the parameters in MQL4PluginSettingsPanel are not initialized properly

**Comment by mfursov** [comment]
Should be fixed in the latest update. Please check.
