### ISSUE TITLE
Only showing russian documentation

### ISSUE THREAD

**Issue by mrhoga** [investflow/mqlidea#11]
When I hover over types for which documentation exists it's always shown in Russian. In the repo, I saw that there seems to be English documentation as well. Can I somehow configure which language to use?

BTW: This plugin is really awesome! I'm using it with MQL5 and though not fully supported it is a pleasure to be able to use Rider for coding. Thank you so much!

**Comment by mfursov** [comment]
Should be fixed in the latest update. + English is now default.
