### ISSUE TITLE
"Identifier expected" and "Unexpected token" errors at an instance declaration

### ISSUE THREAD

**Issue by canaryw1127** [investflow/mqlidea#7]
Hi!

I found the following errors.
It would be great if they were fixed.

Regards,

---

#### 1st error:
![image](https://user-images.githubusercontent.com/17269144/91122331-071d3a80-e6d5-11ea-868d-ce5f498499f5.png)

#### 2nd error:
![image](https://user-images.githubusercontent.com/17269144/91122382-2caa4400-e6d5-11ea-8519-89d35c06d536.png)

#### Code sample:
This code has no compile error.
```C++
#define SOME_CONVERSION(arg) (arg - 1)

class ClassA {
public:
  ClassA(int arg1, int arg2) {};
};

ClassA a(SOME_CONVERSION(1), 2);
```

**Comment by mfursov** [comment]
The parser in the plugin is not very advanced and can't separate constructor calls from function declaration statements.
This way the best solution today would be to avoid false positive results: I will turn off such errors completely.
